blank_issues_enabled: false
contact_links:
  - name: Feature Requests Not Accepted
    url: https://github.com/firstbaseman/smb4-league-import-tool
    about: This tool is feature-complete. Only bug reports will be reviewed.
